version = 3.9.9
runner.dialect = scala3
rewrite.trailingCommas.style = always
rewrite.rules = [Imports]
rewrite.imports.sort = scalastyle
rewrite.imports.groups = [["java\\..*"], ["scala\\..*"], [".*"], ["tdl\\..*"]]
