#
#
#
http://localhost:8080
Content-Type: application/json
-i

listId1 = list1
listId2 = list2
listId3 = list3
listId4 = list4
listId5 = list5
--

#
# Get all lists
#
--
GET /list

#
# Get TodoList
#
--
GET /list/:listId1

#
# POST TodoList
#
--
POST /list/:listId1
{
  "name": "list #1",
  "items": [
    {
      "id": "i1",
      "value": "item1",
      "checked": true
    },
    {
      "id": "i2",
      "value": "item2",
      "checked": false
    },
    {
      "id": "i3",
      "value": "item3",
      "checked": true
    }
  ]
}

#
# POST TodoList/item
#
--
POST /list/:listId1/item/i1
{
  "checked": true
}

##############################################

#
# Get TodoList
#
--
GET /list/:listId2

#
# POST TodoList
#
--
POST /list/:listId2
{
  "name": "list #2",
  "items": [
    {
      "id": "i1",
      "value": "item1",
      "checked": true
    },
    {
      "id": "i2",
      "value": "item2",
      "checked": false
    },
    {
      "id": "i3",
      "value": "item3",
      "checked": true
    },
    {
      "id": "i4",
      "value": "item4",
      "checked": false
    }
  ]
}
