#
#
#
http://localhost:8080
Content-Type: application/json
-i

listId1 = list1
listId2 = list2
listId3 = list3
listId4 = list4
listId5 = list5
listId6 = list6
listId7 = list7
listId8 = list8
--

#
# Get all lists
#
--
GET /list

#
# Get TodoList
#
--
GET /list/:listId1

#
# POST TodoList
#
--
POST /list/:listId1
{
  "name": "list #1",
  "items": [
    {
      "id": "i1",
      "value": "item1",
      "checked": true
    },
    {
      "id": "i2",
      "value": "item2",
      "checked": false
    },
    {
      "id": "i3",
      "value": "item3",
      "checked": true
    }
  ]
}

#
# POST TodoList/item
#
--
POST /list/:listId1/item/i1
{
  "checked": true
}

##############################################

#
# Get TodoList
#
--
GET /list/:listId2

#
# POST TodoList
#
--
POST /list/:listId2
{
  "name": "list #2",
  "items": [
    {
      "id": "i1",
      "value": "item1",
      "checked": true
    },
    {
      "id": "i2",
      "value": "item2",
      "checked": false
    },
    {
      "id": "i3",
      "value": "item3",
      "checked": true
    },
    {
      "id": "i4",
      "value": "item4",
      "checked": false
    }
  ]
}

##############################################

#
# Get TodoList
#
--
GET /list/:listId3

#
# POST TodoList
#
--
POST /list/:listId3
{
  "name": "list #3",
  "items": [
    {
      "id": "i1",
      "value": "item1",
      "checked": true
    },
    {
      "id": "i2",
      "value": "item2",
      "checked": false
    },
    {
      "id": "i3",
      "value": "item3",
      "checked": true
    },
    {
      "id": "i4",
      "value": "item4",
      "checked": false
    }
  ]
}

##############################################

#
# Get TodoList
#
--
GET /list/:listId4

#
# POST TodoList
#
--
POST /list/:listId4
{
  "name": "list #4",
  "items": [
    {
      "id": "i1",
      "value": "item1",
      "checked": true
    },
    {
      "id": "i2",
      "value": "item2",
      "checked": false
    },
    {
      "id": "i3",
      "value": "item3",
      "checked": true
    },
    {
      "id": "i4",
      "value": "item4",
      "checked": false
    }
  ]
}

##############################################

#
# Get TodoList
#
--
GET /list/:listId5

#
# POST TodoList
#
--
POST /list/:listId5
{
  "name": "list #5",
  "items": [
    {
      "id": "i1",
      "value": "item1",
      "checked": true
    },
    {
      "id": "i2",
      "value": "item2",
      "checked": false
    },
    {
      "id": "i3",
      "value": "item3",
      "checked": true
    },
    {
      "id": "i4",
      "value": "item4",
      "checked": false
    }
  ]
}

##############################################

#
# Get TodoList
#
--
GET /list/:listId6

#
# POST TodoList
#
--
POST /list/:listId6
{
  "name": "list #6",
  "items": [
    {
      "id": "i1",
      "value": "item1",
      "checked": true
    },
    {
      "id": "i2",
      "value": "item2",
      "checked": false
    },
    {
      "id": "i3",
      "value": "item3",
      "checked": true
    },
    {
      "id": "i4",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i5",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i6",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i7",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i8",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i9",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i10",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i11",
      "value": "item4",
      "checked": false
    }
  ]
}

##############################################

#
# Get TodoList
#
--
GET /list/:listId7

#
# POST TodoList
#
--
POST /list/:listId7
{
  "name": "list #7",
  "items": [
    {
      "id": "i1",
      "value": "item1",
      "checked": true
    },
    {
      "id": "i2",
      "value": "item2",
      "checked": false
    },
    {
      "id": "i3",
      "value": "item3",
      "checked": true
    },
    {
      "id": "i4",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i5",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i6",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i7",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i8",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i9",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i10",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i11",
      "value": "item4",
      "checked": false
    }
  ]
}

##############################################

#
# Get TodoList
#
--
GET /list/:listId8

#
# POST TodoList
#
--
POST /list/:listId8
{
  "name": "list #8",
  "items": [
    {
      "id": "i1",
      "value": "item1",
      "checked": false
    },
    {
      "id": "i2",
      "value": "item2",
      "checked": false
    },
    {
      "id": "i3",
      "value": "item3",
      "checked": true
    },
    {
      "id": "i4",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i5",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i6",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i7",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i8",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i9",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i10",
      "value": "item4",
      "checked": false
    },
    {
      "id": "i11",
      "value": "item4",
      "checked": false
    }
  ]
}
