//addSbtPlugin("org.typelevel" % "sbt-tpolecat" % "0.5.2")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.10.0")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.11.3")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "2.0.13")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.3.1")
